name: 'feishu bot action'
description: 'message by Feishu bot, super tiny.  run one time cost 1s .support linux macos and window, base node runner not by docker'
author: 'foxundermoon'
inputs:
  url:
    required: true
    description: 'web hook url'
  title:
    required: true
    description: the msg title
  text:
    required: true
    description: the msg body

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: 'blue'
  icon: 'message-square'
