name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              hahahah
              from github action test
              repository: ${{ github.repository }}
              committer: ${{ github.actor }}
              compare: ${{ github.event.compare }}
              job status: ${{ job.status }}
      - uses: ./
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 我是一个标题
                content:
                - - tag: text
                    un_escape: true
                    text: '第一行&nbsp;:'
                  - tag: a
                    text: 超链接 repo
                    href: ${{ github.repository }}
                  - tag: at
                    user_id: ou_18eac85d35a26f989317ad4f02e8bbbb
                - - tag: text
                    text: '第二行 :'
                  - tag: text
                    text: 文本测试
                - - tag: img
                    image_key: d640eeea-4d2f-4cb3-88d8-c964fab53987
                    width: 300
                    height: 300
      - uses: ./
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: share_chat
          content: |
            share_chat_id: oc_f5b1a7eb27ae2c7b6adc2a74faf339ff
      - uses: ./
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: image
          content: |
            image_key: img_ecffc3b9-8f14-400f-a014-05eca1a4310g
      - uses: ./
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: interactive
          card: |
            config:
              wide_screen_mode: true
            header:
              template: blue
              title:
                content: 🍎 HomeLab Release
                tag: plain_text
            elements:
              - tag: markdown
                content: ${{ context.payload.head_commit.message }}
